trigger:
  - develop

resources:
  - repo: self

variables:
  - group: variable-FastAPI

stages:
  - stage: Build
    displayName: Build, push, and deploy stage
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
          - task: Bash@3
            displayName: Pull and Run Docker Container on Remote Host
            inputs:
              targetType: "inline"
              script: |
                sshpass -p '$(sshPassword)' ssh -o StrictHostKeyChecking=no $(sshUsername)@$(sshHost) -p $(sshPort) << EOF
                  az acr login --name $(dockerLogin)
                  /usr/bin/docker stop $(dockerName)
                  /usr/bin/docker rm $(dockerName)
                  /usr/bin/docker pull $(containerRegistry)/$(imageRepository):$(tag)
                  /usr/bin/docker run -d \
                                      --name $(dockerName) \
                                      -p $(port) \
                                      --env MONGO_DATABASE=$(MONGO_DATABASE) \
                                      --env MONGO_HOST=$(MONGO_HOST) \
                                      --env MONGO_PASSWORD=$(MONGO_PASSWORD) \
                                      --env MONGO_USERNAME=$(MONGO_USERNAME) \
                                      --env MS_CLIENT_ID=$(MS_CLIENT_ID) \
                                      --env MS_CLIENT_SECRET=$(MS_CLIENT_SECRET) \
                                      --env MS_CLIENT_SECRET=$(MS_CLIENT_SECRET_) \
                                      --env MS_CLIENT_VALUE_=$(MS_CLIENT_VALUE_) \
                                      --env MS_REDIRECT_URI=$(MS_REDIRECT_URI) \
                                      $(containerRegistry)/$(imageRepository):$(tag)
                EOF
