import os
import sys
import json

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from fastapi import FastAPI, Request
from utils import lifespan
from routes.auth import auth_controller
from routes.page import page_controller
from routes.user import user_controller
from routes.category import category_controller
from routes.work_request import work_request_controller
from routes import index
from db.context import auth_collection

from middlewares import cors_middleware
# from middlewares import static_middleware

app = FastAPI(lifespan=lifespan.lifespan)

cors_middleware.add(app)
# app.add_middleware(rbac.TokenVerifyMiddleware)
# static_middleware.add(app)

app.include_router(index.router)
app.include_router(auth_controller.router)
app.include_router(page_controller.router)
app.include_router(user_controller.router)
app.include_router(work_request_controller.router)
app.include_router(category_controller.router)

@app.get("/ping")
def ping():
    return "pong"

@app.get("/est")
def test():
    test = auth_collection.find_one({"access_token": "eyJ0eXAiOiJKV1QiLCJub25jZSI6IkZZcHhEQmZreHRxYWNRMUY0Vnp2OFBxVEEwQUdmQ3hzWlk1bDZRSmI4UU0iLCJhbGciOiJSUzI1NiIsIng1dCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCIsImtpZCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83ZTY5MGQ5Yi0xZDIwLTRmZmEtOWYyNS0zMzhlMjFkNzViNTAvIiwiaWF0IjoxNzIyOTkxOTk5LCJuYmYiOjE3MjI5OTE5OTksImV4cCI6MTcyMjk5NzM5NCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFZUUFlLzhYQUFBQWlrRytBenhqcFc1MU5yMEthN09uYVhLcjdmV0laemdLWlRMN2YwbjcyczVZYkc1REZYcG45Q0wxaFZHSnVGdnd3L0lCNGFHRHpBYlljYkx5YlJ5cXYxeG5ndEw0eFVkRDE1Nk1SQU0xYkVoc3FkV1ZqMVc3bXk4Y3lzeGVCRUp4YjRqYVY1MEhTejBTa3BaSStIdS9Xc1dzTnFOUVN6TjUvVFFUd3hXUmM5MD0iLCJhbXIiOlsicnNhIiwibWZhIl0sImFwcF9kaXNwbGF5bmFtZSI6Ik1hdmVuTWVtYmVyc1BvcnRhbEFwcCIsImFwcGlkIjoiZDY2YzNmNWYtMjg1Zi00MmE0LTk0ZjctNTc0ZjE1NDA1Njc4IiwiYXBwaWRhY3IiOiIxIiwiZGV2aWNlaWQiOiIwNDc5NzJhNS1jNzRiLTRjMmMtYjJmNi05NjQxYjg1Y2ZmZmUiLCJmYW1pbHlfbmFtZSI6IlBhcmsiLCJnaXZlbl9uYW1lIjoiV2FkZSIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjEyMS4xMzQuMzEuMTA0IiwibmFtZSI6IldhZGUo67CV6rG066WgKSIsIm9pZCI6IjNiYTJjOTllLTI2YTQtNGIxMy04OWNlLTk2YmE4ZWFmNzAwYSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMzkxNjIwNzkzIiwicmgiOiIwLkFWUUFtdzFwZmlBZC1rLWZKVE9PSWRkYlVBTUFBQUFBQUFBQXdBQUFBQUFBQUFCVUFDYy4iLCJzY3AiOiJDcm9zc1RlbmFudEluZm9ybWF0aW9uLlJlYWRCYXNpYy5BbGwgQ3Jvc3NUZW5hbnRVc2VyUHJvZmlsZVNoYXJpbmcuUmVhZFdyaXRlLkFsbCBlbWFpbCBNYW5hZ2VkVGVuYW50cy5SZWFkLkFsbCBvcGVuaWQgUG9saWN5LlJlYWRXcml0ZS5Dcm9zc1RlbmFudEFjY2VzcyBwcm9maWxlIFVzZXIuUmVhZCBVc2VyLlJlYWRCYXNpYy5BbGwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiJ3MFdsenpQSkFvbURjMC1ha3N4TXJiUXpLLXRLQ3VSZHBNRXJwWURZSl9FIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiN2U2OTBkOWItMWQyMC00ZmZhLTlmMjUtMzM4ZTIxZDc1YjUwIiwidW5pcXVlX25hbWUiOiJ3YWRlLnBhcmtAbWF2ZW5jbG91ZHNlcnZpY2UuY29tIiwidXBuIjoid2FkZS5wYXJrQG1hdmVuY2xvdWRzZXJ2aWNlLmNvbSIsInV0aSI6IjNfZUs5VFpxSzB1aGlOeHJxM0VKQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjliODk1ZDkyLTJjZDMtNDRjNy05ZDAyLWE2YWMyZDVlYTVjMyIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfaWRyZWwiOiIxIDgiLCJ4bXNfc3QiOnsic3ViIjoidHJETERKY1lpOGF5a0pFOU1aUC0yV1RtRnhnWU9YTkdVeDlEajdLRGF5dyJ9LCJ4bXNfdGNkdCI6MTQzNTEyMjQzMH0.eCTvwAmaMkkRTuuH7CZhahHYK2cBgSNd6tcUsH4iO5T0zYHqE0uih1TSSBQo6a1fIo2G4EoPxvdbFW7nMzzp04lC6o6_h5OkSF3Dq1CV9p2n1ja5xcw4lUobpFl0nUD4MQxLk7_gDvvYjuOVvlyKCVvlgaqqccM3q6rcQSrw_V7Hu5fYGR70Cua19_jQrIKWOmfiC11b6J4NiHF3WYBJZtdqQtF1ASY94ZpePmaQjoUxoyTFChi8gwYltc4lNoxY6tThjR4byJxwCde5xk_RAP5vbzNhtLWmVniZE6V_daiUR7vKDsC0sV8wla8duQIL9eTZm5ZVYq8sac2igWpDpQ"}, {"_id": 0})
    response_content=json.loads(json.dumps(test, indent=1, default=str))
    return response_content